services:
  database:
    image: mysql:9
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "28306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data: